[workspace]

[package]
name = "dcb_layer_nif"
version = "0.1.0"
edition = "2021"

[lib]
name = "dcb_layer_nif"
crate-type = ["cdylib"]

[features]
default = ["fdb-7_4"]
fdb-7_3 = ["foundationdb/fdb-7_3"]
fdb-7_4 = ["foundationdb/fdb-7_4"]

[dependencies]
dcb-layer = { version = "0.2.0", path = "../../../dcb-layer" }
foundationdb = { version = "0.10", features = ["embedded-fdb-include"] }
once_cell = "1.21.4"
rustler = "0.35"
tokio = { version = "1", features = ["full"] }
